output "admin_password" {
  description = <<-EOT
  Autogenerated password for the ArgoCD admin user.
  This output is marked as sensitive by Terraform and therefore is displayed masked in the console output.
  For information on how to display it unmasked take a look at [this article](https://support.hashicorp.com/hc/en-us/articles/5175257151891-How-to-output-sensitive-data-with-Terraform).
  EOT
  value       = random_password.argocd_admin_password.result
}

output "release_status" {
  description = "Status of the deployed ArgoCD Helm chart"
  value       = helm_release.argocd.metadata
}
