output "admin_password" {
  description = "Autogenerated password for the ArgoCD admin user"
  value       = module.argocd.admin_password
  sensitive   = true
}

output "release_status" {
  description = "Status of the deployed ArgoCD Helm chart"
  value       = module.argocd.release_status
}
